### ISSUE TITLE
Fatal error when used in conjuction with GiveWP Recurring Donations

### ISSUE THREAD

**Issue by pdobrescu** [imath/wp-statuses#58]
Hello and thanks for the great plugin!

I would like to report a fatal error that is thrown by WP Statuses when the GiveWP Recurring Donations plugin is active, here's the error:

```
PHP Fatal error:  Uncaught Error: Call to undefined method stdClass::is_builtin() in /wp-content/plugins/wp-statuses/inc/core/functions.php:394
Stack trace:
#0 /wp-content/plugins/wp-statuses/inc/core/functions.php(411): wp_statuses_get_customs()
#1 /wp-content/plugins/wp-statuses/inc/core/functions.php(500): wp_statuses_get_customs_post_types()
#2 /wp-includes/class-wp-hook.php(303): wp_statuses_register_post_types_field()
#3 /wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters()
#4 /wp-includes/plugin.php(470): WP_Hook->do_action()
#5 /wp-includes/rest-api.php(537): do_action()
#6 /wp-includes/rest-api.php(363): rest_get_server()
#7 /wp-includes/class-wp-h in /wp-content/plugins/wp-statuses/inc/core/functions.php on line 394
```

Can you please have a look and let me know if there is a way to get it resolved from your end? I'll obviously contact the GiveWP team as well and hopefully we can sort this out.

Please let me know what other details you need.

**Comment by imath** [comment]
This was fixed here #53
